export default {
    GET_DISCOVER_REQUEST:'GET_DISCOVER_REQUEST',
    DISCOVER_RESULT:'DISCOVER_RESULT',
    DISCOVER_MORE:'DISCOVER_MORE',
    DISCOVER_GENRES:'DISCOVER_GENRES',
    DISCOVER_SORT:'DISCOVER_SORT',
    GET_GENRES:'GET_GENRES',
    GET_MOVES:'GET_MOVES'
}