export default {
    GET_DISCOVER_REQUEST:'GET_DISCOVER_REQUEST',
    DISCOVER_RESULT:'DISCOVER_RESULT',
    GET_DISCOVER_MORE_REQUEST:'GET_DISCOVER_MORE_REQUEST',
    DISCOVER_MORE_RESULT:'DISCOVER_MORE_RESULT',
    GET_GENRES:'GET_GENRES',
    GET_MOVES:'GET_MOVES',
    GET_DETAILFILM_REQUEST:'GET_DETAILFILM_REQUEST',
    DETAILFILM_RESULT:'DETAILFILM_RESULT'

}