name: Build & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
        with:
          branch: gh-pages
          folder: build      